#!/bin/sh
# board installer — installs a `board` command that runs this repo with bun.
#
#   ./install.sh                interactive install
#   ./install.sh --yes          non-interactive, accept defaults
#   ./install.sh --skill        also install the Claude Code skill globally
#   ./install.sh --no-skill     never install the skill
#   ./install.sh --uninstall    remove the launcher (and global skill)
#
# Env: BOARD_BIN_DIR overrides the launcher directory (default ~/.local/bin).
# Uses charmbracelet gum for prompts/styling when available; plain sh otherwise.
set -eu

REPO_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BIN_DIR="${BOARD_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/board"
SKILL_SRC="$REPO_DIR/.claude/skills/board"
SKILL_DST="$HOME/.claude/skills/board"

YES=0
SKILL=ask
UNINSTALL=0
for arg in "$@"; do
  case "$arg" in
    --yes|-y) YES=1 ;;
    --skill) SKILL=yes ;;
    --no-skill) SKILL=no ;;
    --uninstall) UNINSTALL=1 ;;
    --help|-h)
      sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "unknown option: $arg (try --help)" >&2; exit 1 ;;
  esac
done

HAS_GUM=0
command -v gum >/dev/null 2>&1 && [ -t 1 ] && HAS_GUM=1

say() { printf '%s\n' "$*"; }

ok() { # checkmark line
  if [ "$HAS_GUM" = 1 ]; then
    gum style --foreground 42 "✓ $*"
  else
    say "✓ $*"
  fi
}

warn() {
  if [ "$HAS_GUM" = 1 ]; then
    gum style --foreground 214 "! $*"
  else
    say "! $*"
  fi
}

fail() {
  if [ "$HAS_GUM" = 1 ]; then
    gum style --foreground 196 "✗ $*" >&2
  else
    say "✗ $*" >&2
  fi
  exit 1
}

header() {
  if [ "$HAS_GUM" = 1 ]; then
    gum style --border rounded --padding "0 2" --margin "1 0" --foreground 212 --border-foreground 212 "$@"
  else
    say ""
    say "== $* =="
  fi
}

confirm() { # confirm "question" -> 0 yes / 1 no; non-interactive or --yes = yes
  [ "$YES" = 1 ] && return 0
  [ -t 0 ] || return 0
  if [ "$HAS_GUM" = 1 ]; then
    gum confirm "$1"
  else
    printf '%s [Y/n] ' "$1"
    read -r answer || answer=""
    case "$answer" in n|N|no|NO) return 1 ;; *) return 0 ;; esac
  fi
}

if [ "$UNINSTALL" = 1 ]; then
  header "board · uninstall"
  removed=0
  if [ -e "$LAUNCHER" ]; then rm -f "$LAUNCHER"; ok "removed $LAUNCHER"; removed=1; fi
  if [ -d "$SKILL_DST" ]; then rm -rf "$SKILL_DST"; ok "removed $SKILL_DST"; removed=1; fi
  [ "$removed" = 0 ] && say "nothing to remove"
  warn "room data in ~/.board was left untouched"
  exit 0
fi

if [ ! -f "$REPO_DIR/src/cli.ts" ]; then
  fail "$REPO_DIR does not look like the board repo (src/cli.ts missing)"
fi

header "board · install"

# --- resolve bun -----------------------------------------------------------
BUN_BIN=""
if command -v bun >/dev/null 2>&1; then
  BUN_BIN=$(command -v bun)
elif [ -x "$HOME/.bun/bin/bun" ]; then
  BUN_BIN="$HOME/.bun/bin/bun"
else
  warn "board needs bun (https://bun.sh) and it isn't installed."
  if confirm "Install bun now via the official installer?"; then
    if [ "$HAS_GUM" = 1 ]; then
      gum spin --spinner dot --title "Installing bun…" --show-error -- \
        sh -c 'curl -fsSL https://bun.sh/install | bash'
    else
      curl -fsSL https://bun.sh/install | bash
    fi
    BUN_BIN="$HOME/.bun/bin/bun"
    [ -x "$BUN_BIN" ] || fail "bun install did not produce $BUN_BIN"
  else
    fail "install bun first, then re-run ./install.sh"
  fi
fi
ok "bun: $BUN_BIN"

# --- launcher --------------------------------------------------------------
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# launcher generated by board/install.sh — repo: $REPO_DIR
exec "$BUN_BIN" "$REPO_DIR/src/cli.ts" "\$@"
EOF
chmod +x "$LAUNCHER"
"$LAUNCHER" help >/dev/null || fail "launcher smoke test failed"
ok "launcher: $LAUNCHER → $REPO_DIR"

# --- Claude Code skill (optional) ------------------------------------------
if [ "$SKILL" = "ask" ]; then
  if confirm "Install the Claude Code skill globally (~/.claude/skills/board)?"; then
    SKILL=yes
  else
    SKILL=no
  fi
fi
if [ "$SKILL" = "yes" ]; then
  mkdir -p "$HOME/.claude/skills"
  rm -rf "$SKILL_DST"
  cp -R "$SKILL_SRC" "$SKILL_DST"
  ok "skill: $SKILL_DST"
fi

# --- PATH check ------------------------------------------------------------
case ":$PATH:" in
  *":$BIN_DIR:"*)
    header "done — try: board join lobby"
    ;;
  *)
    warn "$BIN_DIR is not on your PATH. Add it:"
    say "  zsh/bash:  echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc"
    say "  nushell:   in config.nu:  \$env.PATH = (\$env.PATH | prepend '$BIN_DIR')"
    say "  fish:      fish_add_path $BIN_DIR"
    header "done — open a new shell, then: board join lobby"
    ;;
esac
